name: 'Slack Greeting'
description: 'Send inspirational quotes to slack channel - quotes from https://type.fit/api/quotes'
author: 'Mua Rachmann'
branding:
  icon: 'zap'
  color: 'green'
inputs:
  SLACK_CLIENT_TOKEN:
    description: 'Slack client token to be able to post in the channel'
    required: true
runs:
  using: 'node12'
  main: 'src/index.js'